/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as AuthenticatedSincronizacaoRouteImport } from './routes/_authenticated/sincronizacao'
import { Route as AuthenticatedRelatoriosMotoristaRouteImport } from './routes/_authenticated/relatorios-motorista'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedPendentesRouteImport } from './routes/_authenticated/pendentes'
import { Route as AuthenticatedOperacaoRouteImport } from './routes/_authenticated/operacao'
import { Route as AuthenticatedMotoristasRouteImport } from './routes/_authenticated/motoristas'
import { Route as AuthenticatedMinhasEntregasRouteImport } from './routes/_authenticated/minhas-entregas'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsumoPrecisoRouteImport } from './routes/_authenticated/consumo-preciso'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAfericoesRouteImport } from './routes/_authenticated/afericoes'
import { Route as AuthenticatedAcessoExpiradoRouteImport } from './routes/_authenticated/acesso-expirado'
import { Route as AuthenticatedAbastecimentoRouteImport } from './routes/_authenticated/abastecimento'
import { Route as AuthenticatedPneusIndexRouteImport } from './routes/_authenticated/pneus.index'
import { Route as AuthenticatedEntregaIndexRouteImport } from './routes/_authenticated/entrega.index'
import { Route as AuthenticatedDespesasIndexRouteImport } from './routes/_authenticated/despesas.index'
import { Route as AuthenticatedSincronizacaoHistoricoRouteImport } from './routes/_authenticated/sincronizacao.historico'
import { Route as AuthenticatedPneusRelatorioRouteImport } from './routes/_authenticated/pneus.relatorio'
import { Route as AuthenticatedPneusInstalarRouteImport } from './routes/_authenticated/pneus.instalar'
import { Route as AuthenticatedDespesasNovaRouteImport } from './routes/_authenticated/despesas.nova'
import { Route as AuthenticatedPneusRemoverIdRouteImport } from './routes/_authenticated/pneus.remover.$id'
import { Route as AuthenticatedEntregaIdFinalizarRouteImport } from './routes/_authenticated/entrega.$id.finalizar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSincronizacaoRoute =
  AuthenticatedSincronizacaoRouteImport.update({
    id: '/sincronizacao',
    path: '/sincronizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosMotoristaRoute =
  AuthenticatedRelatoriosMotoristaRouteImport.update({
    id: '/relatorios-motorista',
    path: '/relatorios-motorista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendentesRoute = AuthenticatedPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacaoRoute = AuthenticatedOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristasRoute = AuthenticatedMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasEntregasRoute =
  AuthenticatedMinhasEntregasRouteImport.update({
    id: '/minhas-entregas',
    path: '/minhas-entregas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsumoPrecisoRoute =
  AuthenticatedConsumoPrecisoRouteImport.update({
    id: '/consumo-preciso',
    path: '/consumo-preciso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAfericoesRoute = AuthenticatedAfericoesRouteImport.update({
  id: '/afericoes',
  path: '/afericoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcessoExpiradoRoute =
  AuthenticatedAcessoExpiradoRouteImport.update({
    id: '/acesso-expirado',
    path: '/acesso-expirado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAbastecimentoRoute =
  AuthenticatedAbastecimentoRouteImport.update({
    id: '/abastecimento',
    path: '/abastecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPneusIndexRoute = AuthenticatedPneusIndexRouteImport.update({
  id: '/pneus/',
  path: '/pneus/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregaIndexRoute =
  AuthenticatedEntregaIndexRouteImport.update({
    id: '/entrega/',
    path: '/entrega/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespesasIndexRoute =
  AuthenticatedDespesasIndexRouteImport.update({
    id: '/despesas/',
    path: '/despesas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSincronizacaoHistoricoRoute =
  AuthenticatedSincronizacaoHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedSincronizacaoRoute,
  } as any)
const AuthenticatedPneusRelatorioRoute =
  AuthenticatedPneusRelatorioRouteImport.update({
    id: '/pneus/relatorio',
    path: '/pneus/relatorio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPneusInstalarRoute =
  AuthenticatedPneusInstalarRouteImport.update({
    id: '/pneus/instalar',
    path: '/pneus/instalar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespesasNovaRoute =
  AuthenticatedDespesasNovaRouteImport.update({
    id: '/despesas/nova',
    path: '/despesas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPneusRemoverIdRoute =
  AuthenticatedPneusRemoverIdRouteImport.update({
    id: '/pneus/remover/$id',
    path: '/pneus/remover/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntregaIdFinalizarRoute =
  AuthenticatedEntregaIdFinalizarRouteImport.update({
    id: '/entrega/$id/finalizar',
    path: '/entrega/$id/finalizar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/acesso-expirado': typeof AuthenticatedAcessoExpiradoRoute
  '/afericoes': typeof AuthenticatedAfericoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consumo-preciso': typeof AuthenticatedConsumoPrecisoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/master': typeof AuthenticatedMasterRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/minhas-entregas': typeof AuthenticatedMinhasEntregasRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/pendentes': typeof AuthenticatedPendentesRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-motorista': typeof AuthenticatedRelatoriosMotoristaRoute
  '/sincronizacao': typeof AuthenticatedSincronizacaoRouteWithChildren
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/despesas/nova': typeof AuthenticatedDespesasNovaRoute
  '/pneus/instalar': typeof AuthenticatedPneusInstalarRoute
  '/pneus/relatorio': typeof AuthenticatedPneusRelatorioRoute
  '/sincronizacao/historico': typeof AuthenticatedSincronizacaoHistoricoRoute
  '/despesas/': typeof AuthenticatedDespesasIndexRoute
  '/entrega/': typeof AuthenticatedEntregaIndexRoute
  '/pneus/': typeof AuthenticatedPneusIndexRoute
  '/entrega/$id/finalizar': typeof AuthenticatedEntregaIdFinalizarRoute
  '/pneus/remover/$id': typeof AuthenticatedPneusRemoverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/acesso-expirado': typeof AuthenticatedAcessoExpiradoRoute
  '/afericoes': typeof AuthenticatedAfericoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consumo-preciso': typeof AuthenticatedConsumoPrecisoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/master': typeof AuthenticatedMasterRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/minhas-entregas': typeof AuthenticatedMinhasEntregasRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/pendentes': typeof AuthenticatedPendentesRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-motorista': typeof AuthenticatedRelatoriosMotoristaRoute
  '/sincronizacao': typeof AuthenticatedSincronizacaoRouteWithChildren
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/despesas/nova': typeof AuthenticatedDespesasNovaRoute
  '/pneus/instalar': typeof AuthenticatedPneusInstalarRoute
  '/pneus/relatorio': typeof AuthenticatedPneusRelatorioRoute
  '/sincronizacao/historico': typeof AuthenticatedSincronizacaoHistoricoRoute
  '/despesas': typeof AuthenticatedDespesasIndexRoute
  '/entrega': typeof AuthenticatedEntregaIndexRoute
  '/pneus': typeof AuthenticatedPneusIndexRoute
  '/entrega/$id/finalizar': typeof AuthenticatedEntregaIdFinalizarRoute
  '/pneus/remover/$id': typeof AuthenticatedPneusRemoverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/_authenticated/acesso-expirado': typeof AuthenticatedAcessoExpiradoRoute
  '/_authenticated/afericoes': typeof AuthenticatedAfericoesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/consumo-preciso': typeof AuthenticatedConsumoPrecisoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/master': typeof AuthenticatedMasterRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/minhas-entregas': typeof AuthenticatedMinhasEntregasRoute
  '/_authenticated/motoristas': typeof AuthenticatedMotoristasRoute
  '/_authenticated/operacao': typeof AuthenticatedOperacaoRoute
  '/_authenticated/pendentes': typeof AuthenticatedPendentesRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/relatorios-motorista': typeof AuthenticatedRelatoriosMotoristaRoute
  '/_authenticated/sincronizacao': typeof AuthenticatedSincronizacaoRouteWithChildren
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/_authenticated/despesas/nova': typeof AuthenticatedDespesasNovaRoute
  '/_authenticated/pneus/instalar': typeof AuthenticatedPneusInstalarRoute
  '/_authenticated/pneus/relatorio': typeof AuthenticatedPneusRelatorioRoute
  '/_authenticated/sincronizacao/historico': typeof AuthenticatedSincronizacaoHistoricoRoute
  '/_authenticated/despesas/': typeof AuthenticatedDespesasIndexRoute
  '/_authenticated/entrega/': typeof AuthenticatedEntregaIndexRoute
  '/_authenticated/pneus/': typeof AuthenticatedPneusIndexRoute
  '/_authenticated/entrega/$id/finalizar': typeof AuthenticatedEntregaIdFinalizarRoute
  '/_authenticated/pneus/remover/$id': typeof AuthenticatedPneusRemoverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/abastecimento'
    | '/acesso-expirado'
    | '/afericoes'
    | '/clientes'
    | '/configuracoes'
    | '/consumo-preciso'
    | '/dashboard'
    | '/entregas'
    | '/financeiro'
    | '/master'
    | '/materiais'
    | '/minhas-entregas'
    | '/motoristas'
    | '/operacao'
    | '/pendentes'
    | '/permissoes'
    | '/relatorios'
    | '/relatorios-motorista'
    | '/sincronizacao'
    | '/trocar-senha'
    | '/veiculos'
    | '/despesas/nova'
    | '/pneus/instalar'
    | '/pneus/relatorio'
    | '/sincronizacao/historico'
    | '/despesas/'
    | '/entrega/'
    | '/pneus/'
    | '/entrega/$id/finalizar'
    | '/pneus/remover/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/abastecimento'
    | '/acesso-expirado'
    | '/afericoes'
    | '/clientes'
    | '/configuracoes'
    | '/consumo-preciso'
    | '/dashboard'
    | '/entregas'
    | '/financeiro'
    | '/master'
    | '/materiais'
    | '/minhas-entregas'
    | '/motoristas'
    | '/operacao'
    | '/pendentes'
    | '/permissoes'
    | '/relatorios'
    | '/relatorios-motorista'
    | '/sincronizacao'
    | '/trocar-senha'
    | '/veiculos'
    | '/despesas/nova'
    | '/pneus/instalar'
    | '/pneus/relatorio'
    | '/sincronizacao/historico'
    | '/despesas'
    | '/entrega'
    | '/pneus'
    | '/entrega/$id/finalizar'
    | '/pneus/remover/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/abastecimento'
    | '/_authenticated/acesso-expirado'
    | '/_authenticated/afericoes'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/consumo-preciso'
    | '/_authenticated/dashboard'
    | '/_authenticated/entregas'
    | '/_authenticated/financeiro'
    | '/_authenticated/master'
    | '/_authenticated/materiais'
    | '/_authenticated/minhas-entregas'
    | '/_authenticated/motoristas'
    | '/_authenticated/operacao'
    | '/_authenticated/pendentes'
    | '/_authenticated/permissoes'
    | '/_authenticated/relatorios'
    | '/_authenticated/relatorios-motorista'
    | '/_authenticated/sincronizacao'
    | '/_authenticated/trocar-senha'
    | '/_authenticated/veiculos'
    | '/_authenticated/despesas/nova'
    | '/_authenticated/pneus/instalar'
    | '/_authenticated/pneus/relatorio'
    | '/_authenticated/sincronizacao/historico'
    | '/_authenticated/despesas/'
    | '/_authenticated/entrega/'
    | '/_authenticated/pneus/'
    | '/_authenticated/entrega/$id/finalizar'
    | '/_authenticated/pneus/remover/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sincronizacao': {
      id: '/_authenticated/sincronizacao'
      path: '/sincronizacao'
      fullPath: '/sincronizacao'
      preLoaderRoute: typeof AuthenticatedSincronizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios-motorista': {
      id: '/_authenticated/relatorios-motorista'
      path: '/relatorios-motorista'
      fullPath: '/relatorios-motorista'
      preLoaderRoute: typeof AuthenticatedRelatoriosMotoristaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendentes': {
      id: '/_authenticated/pendentes'
      path: '/pendentes'
      fullPath: '/pendentes'
      preLoaderRoute: typeof AuthenticatedPendentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao': {
      id: '/_authenticated/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof AuthenticatedOperacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motoristas': {
      id: '/_authenticated/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof AuthenticatedMotoristasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-entregas': {
      id: '/_authenticated/minhas-entregas'
      path: '/minhas-entregas'
      fullPath: '/minhas-entregas'
      preLoaderRoute: typeof AuthenticatedMinhasEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consumo-preciso': {
      id: '/_authenticated/consumo-preciso'
      path: '/consumo-preciso'
      fullPath: '/consumo-preciso'
      preLoaderRoute: typeof AuthenticatedConsumoPrecisoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/afericoes': {
      id: '/_authenticated/afericoes'
      path: '/afericoes'
      fullPath: '/afericoes'
      preLoaderRoute: typeof AuthenticatedAfericoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acesso-expirado': {
      id: '/_authenticated/acesso-expirado'
      path: '/acesso-expirado'
      fullPath: '/acesso-expirado'
      preLoaderRoute: typeof AuthenticatedAcessoExpiradoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimento': {
      id: '/_authenticated/abastecimento'
      path: '/abastecimento'
      fullPath: '/abastecimento'
      preLoaderRoute: typeof AuthenticatedAbastecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pneus/': {
      id: '/_authenticated/pneus/'
      path: '/pneus'
      fullPath: '/pneus/'
      preLoaderRoute: typeof AuthenticatedPneusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrega/': {
      id: '/_authenticated/entrega/'
      path: '/entrega'
      fullPath: '/entrega/'
      preLoaderRoute: typeof AuthenticatedEntregaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas/': {
      id: '/_authenticated/despesas/'
      path: '/despesas'
      fullPath: '/despesas/'
      preLoaderRoute: typeof AuthenticatedDespesasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sincronizacao/historico': {
      id: '/_authenticated/sincronizacao/historico'
      path: '/historico'
      fullPath: '/sincronizacao/historico'
      preLoaderRoute: typeof AuthenticatedSincronizacaoHistoricoRouteImport
      parentRoute: typeof AuthenticatedSincronizacaoRoute
    }
    '/_authenticated/pneus/relatorio': {
      id: '/_authenticated/pneus/relatorio'
      path: '/pneus/relatorio'
      fullPath: '/pneus/relatorio'
      preLoaderRoute: typeof AuthenticatedPneusRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pneus/instalar': {
      id: '/_authenticated/pneus/instalar'
      path: '/pneus/instalar'
      fullPath: '/pneus/instalar'
      preLoaderRoute: typeof AuthenticatedPneusInstalarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas/nova': {
      id: '/_authenticated/despesas/nova'
      path: '/despesas/nova'
      fullPath: '/despesas/nova'
      preLoaderRoute: typeof AuthenticatedDespesasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pneus/remover/$id': {
      id: '/_authenticated/pneus/remover/$id'
      path: '/pneus/remover/$id'
      fullPath: '/pneus/remover/$id'
      preLoaderRoute: typeof AuthenticatedPneusRemoverIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrega/$id/finalizar': {
      id: '/_authenticated/entrega/$id/finalizar'
      path: '/entrega/$id/finalizar'
      fullPath: '/entrega/$id/finalizar'
      preLoaderRoute: typeof AuthenticatedEntregaIdFinalizarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSincronizacaoRouteChildren {
  AuthenticatedSincronizacaoHistoricoRoute: typeof AuthenticatedSincronizacaoHistoricoRoute
}

const AuthenticatedSincronizacaoRouteChildren: AuthenticatedSincronizacaoRouteChildren =
  {
    AuthenticatedSincronizacaoHistoricoRoute:
      AuthenticatedSincronizacaoHistoricoRoute,
  }

const AuthenticatedSincronizacaoRouteWithChildren =
  AuthenticatedSincronizacaoRoute._addFileChildren(
    AuthenticatedSincronizacaoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbastecimentoRoute: typeof AuthenticatedAbastecimentoRoute
  AuthenticatedAcessoExpiradoRoute: typeof AuthenticatedAcessoExpiradoRoute
  AuthenticatedAfericoesRoute: typeof AuthenticatedAfericoesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConsumoPrecisoRoute: typeof AuthenticatedConsumoPrecisoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedMinhasEntregasRoute: typeof AuthenticatedMinhasEntregasRoute
  AuthenticatedMotoristasRoute: typeof AuthenticatedMotoristasRoute
  AuthenticatedOperacaoRoute: typeof AuthenticatedOperacaoRoute
  AuthenticatedPendentesRoute: typeof AuthenticatedPendentesRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRelatoriosMotoristaRoute: typeof AuthenticatedRelatoriosMotoristaRoute
  AuthenticatedSincronizacaoRoute: typeof AuthenticatedSincronizacaoRouteWithChildren
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedDespesasNovaRoute: typeof AuthenticatedDespesasNovaRoute
  AuthenticatedPneusInstalarRoute: typeof AuthenticatedPneusInstalarRoute
  AuthenticatedPneusRelatorioRoute: typeof AuthenticatedPneusRelatorioRoute
  AuthenticatedDespesasIndexRoute: typeof AuthenticatedDespesasIndexRoute
  AuthenticatedEntregaIndexRoute: typeof AuthenticatedEntregaIndexRoute
  AuthenticatedPneusIndexRoute: typeof AuthenticatedPneusIndexRoute
  AuthenticatedEntregaIdFinalizarRoute: typeof AuthenticatedEntregaIdFinalizarRoute
  AuthenticatedPneusRemoverIdRoute: typeof AuthenticatedPneusRemoverIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbastecimentoRoute: AuthenticatedAbastecimentoRoute,
  AuthenticatedAcessoExpiradoRoute: AuthenticatedAcessoExpiradoRoute,
  AuthenticatedAfericoesRoute: AuthenticatedAfericoesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConsumoPrecisoRoute: AuthenticatedConsumoPrecisoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMasterRoute: AuthenticatedMasterRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedMinhasEntregasRoute: AuthenticatedMinhasEntregasRoute,
  AuthenticatedMotoristasRoute: AuthenticatedMotoristasRoute,
  AuthenticatedOperacaoRoute: AuthenticatedOperacaoRoute,
  AuthenticatedPendentesRoute: AuthenticatedPendentesRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRelatoriosMotoristaRoute: AuthenticatedRelatoriosMotoristaRoute,
  AuthenticatedSincronizacaoRoute: AuthenticatedSincronizacaoRouteWithChildren,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedDespesasNovaRoute: AuthenticatedDespesasNovaRoute,
  AuthenticatedPneusInstalarRoute: AuthenticatedPneusInstalarRoute,
  AuthenticatedPneusRelatorioRoute: AuthenticatedPneusRelatorioRoute,
  AuthenticatedDespesasIndexRoute: AuthenticatedDespesasIndexRoute,
  AuthenticatedEntregaIndexRoute: AuthenticatedEntregaIndexRoute,
  AuthenticatedPneusIndexRoute: AuthenticatedPneusIndexRoute,
  AuthenticatedEntregaIdFinalizarRoute: AuthenticatedEntregaIdFinalizarRoute,
  AuthenticatedPneusRemoverIdRoute: AuthenticatedPneusRemoverIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
